import type { Metadata } from "next";
import Link from "next/link";
import TopNavBar from "../components/TopNavBar";
import Footer from "../components/Footer";
import BackToTopButton from "../components/BackToTopButton";
import FAQAccordion from "../components/FAQAccordion";
import Breadcrumb from "../components/Breadcrumb";
import Sidebar from "../components/Sidebar";
import SerifFontsClient from "./SerifFontsClientLazy";

export const metadata: Metadata = {
  title: { absolute: "Serif Fonts Generator - Copy and Paste Serif Text Styles" },
  description:
    "Convert text into serif fonts you can copy and paste. Explore 15 unicode styles and 34 serif font types, including Slab, Didone, Modern, and Old Style.",
  alternates: {
    canonical: "https://www.aestheticletters.com/serif-fonts",
  },
  openGraph: {
    siteName: "Aesthetic Letters",
    type: "website",
    url: "https://www.aestheticletters.com/serif-fonts",
    title: "Serif Fonts Generator - Copy and Paste Serif Text Styles",
    description:
      "Convert text into serif fonts you can copy and paste. Explore 15 unicode styles and 34 serif font types, including Slab, Didone, Modern, and Old Style.",
    images: [{ url: "/serif-fonts-og.jpg", width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Serif Fonts Generator - Copy and Paste Serif Text Styles",
    description:
      "Convert text into serif fonts you can copy and paste. Explore 15 unicode styles and 34 serif font types, including Slab, Didone, Modern, and Old Style.",
    images: ["/serif-fonts-og.jpg"],
  },
};

const faqs = [
  {
    question: "Are these serif fonts free to use?",
    answer:
      "Yes. The unicode text generated by this tool can generally be copied and pasted freely for personal use. Individual font licenses may apply to traditional downloadable fonts.",
  },
  {
    question: "Do serif styles work on Instagram?",
    answer:
      "Yes. Most unicode serif styles work in Instagram bios, captions, comments, and usernames, although support can vary by device.",
  },
  {
    question: "Why do Serif letters look different when pasted?",
    answer:
      "The generator uses unicode characters rather than traditional font files. Different platforms may render some characters slightly differently.",
  },
  {
    question: "Can I use these styles in my Twitter bio?",
    answer:
      "Yes. Most serif unicode styles can be used in X (formerly Twitter) bios, display names, and posts.",
  },
  {
    question: "Do these fonts work on Discord?",
    answer:
      "Yes. Many unicode serif typefaces display correctly on Discord usernames, profiles, and messages.",
  },
  {
    question: "What is the best serif typeface font for social media?",
    answer:
      "There is no single best choice. Bold Serif, Italic Serif, Small Caps, and elegant styles are among the most popular options.",
  },
  {
    question: "Are these unicode fonts accessible?",
    answer:
      "In most cases they are accessible, but some screen readers may interpret certain decorative unicode characters differently than standard text.",
  },
  {
    question: "Which serif font style looks most professional?",
    answer:
      "Classic serif fonts such as Georgia, Garamond, Baskerville, and Merriweather are often considered highly professional.",
  },
  {
    question: "What are the most famous serif typefaces?",
    answer:
      "Some of the most famous serif typefaces include Times New Roman, Garamond, Georgia, Baskerville, Bodoni, and Playfair Display.",
  },
  {
    question: "How are unicode serif characters created?",
    answer:
      "They are defined within the unicode standard, which assigns unique code points to thousands of characters, including mathematical and stylistic letter variations.",
  },
  {
    question: "Can I use serif fonts in Google Docs or Word?",
    answer:
      "Traditional serif fonts work directly in Google Docs and Microsoft Word. Unicode serif text can also be pasted into many documents, although appearance may vary depending on font support.",
  },
];

const serifVsSansSerif = [
  { feature: "Appearance", serif: "Individual letters include short finishing details known as serifs, which give the typeface a more traditional appearance.", sansSerif: "Letters have clean edges without decorative strokes." },
  { feature: "Style", serif: "Traditional, classic, and elegant.", sansSerif: "Modern, simple, and minimalist." },
  { feature: "Common Uses", serif: "Books, magazines, newspapers, luxury branding, and editorial design.", sansSerif: "Websites, mobile apps, user interfaces, and modern branding." },
  { feature: "Readability", serif: "Often preferred for long-form reading and print materials.", sansSerif: "Often preferred for screens and digital interfaces." },
  { feature: "Brand Personality", serif: "Professional, trustworthy, formal, and established.", sansSerif: "Friendly, clean, innovative, and contemporary." },
  { feature: "Examples", serif: "Georgia, Garamond, Baskerville, Merriweather.", sansSerif: "Arial, Helvetica, Roboto, Open Sans." },
  { feature: "Best For", serif: "Editorial content, publishing, luxury brands, and formal designs.", sansSerif: "Websites, apps, startups, technology brands, and modern layouts." },
];

export default function SerifFontsPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": "https://www.aestheticletters.com/serif-fonts#webpage",
        url: "https://www.aestheticletters.com/serif-fonts",
        name: "Serif Fonts Generator - Copy and Paste Serif Text Styles",
        description: "Convert text into serif fonts you can copy and paste. Explore 15 unicode styles and 34 serif font types, including Slab, Didone, Modern, and Old Style.",
        headline: "Serif Fonts Generator \u2014 Copy & Paste Serif Text",
        inLanguage: "en",
        breadcrumb: {
          "@id": "https://www.aestheticletters.com/serif-fonts#breadcrumb",
        },
      },
      {
        "@type": "SoftwareApplication",
        "@id": "https://www.aestheticletters.com/serif-fonts#softwareapp",
        name: "Serif Fonts Generator",
        url: "https://www.aestheticletters.com/serif-fonts",
        applicationCategory: "UtilitiesApplication",
        operatingSystem: "All",
        offers: {
          "@type": "Offer",
          price: "0.00",
          priceCurrency: "USD",
        },
      },
      {
        "@type": "BreadcrumbList",
        "@id": "https://www.aestheticletters.com/serif-fonts#breadcrumb",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: "Home Page",
            item: "https://www.aestheticletters.com/",
          },
          {
            "@type": "ListItem",
            position: 2,
            name: "All Tools",
            item: "https://www.aestheticletters.com/all-tools",
          },
          {
            "@type": "ListItem",
            position: 3,
            name: "Serif Fonts",
            item: "https://www.aestheticletters.com/serif-fonts",
          },
        ],
      },
      {
        "@type": "FAQPage",
        "@id": "https://www.aestheticletters.com/serif-fonts#faq",
        mainEntity: faqs.map((faq) => ({
          "@type": "Question",
          name: faq.question,
          acceptedAnswer: {
            "@type": "Answer",
            text: faq.answer,
          },
        })),
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <TopNavBar />
      <main id="main-content" className="pt-[5.5rem]">
        <Breadcrumb
          items={[
            { label: "Home", href: "/" },
            { label: "All Tools", href: "/all-tools" },
            { label: "Serif Fonts", href: "/serif-fonts" },
          ]}
        />
        {/* Hero Section */}
        <section className="max-w-[1440px] mx-auto px-4 md:px-[150px] pt-8 pb-4 md:pt-10 md:pb-6 text-center">
          <h1 className="font-headline text-2xl md:text-5xl font-bold tracking-tight leading-tight text-on-background mb-2 md:mb-3">
            Serif Fonts Generator — Copy &amp; Paste Serif Text
          </h1>
          <p className="font-body text-on-surface-variant max-w-2xl mx-auto mb-4 md:mb-4 text-sm md:text-lg">
            Generate serif fonts in 12+ copy and paste styles, explore classic and modern typefaces,
            and find the right look for profiles, posts, and creative projects.
          </p>
        </section>

        {/* Interactive Generator */}
        <SerifFontsClient />

        {/* SEO Content Section */}
        <section className="max-w-[1440px] mx-auto px-4 md:px-[150px] py-24 bg-surface-container-low">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-16">
            {/* Main Content */}
            <div className="lg:col-span-8 flex flex-col gap-16">

              {/* Intro */}
              <article>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  Serif fonts are known for their classic, neat, and professional appearance. They are commonly used in
                  books, magazines, branding, and online content where readability and style matter.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  This serif text generator helps you create serif-style text that can be copied and pasted into social
                  media profiles, usernames, messages, and other online platforms.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-4">
                  This tool includes two types of serif styles:
                </p>
                <ul className="space-y-3 mb-6">
                  {[
                    "12+ Unicode serif typefaces that can be copied and pasted instantly.",
                    "30+ Google serif fonts organized into 8 major serif categories for inspiration and design projects.",
                  ].map((item) => (
                    <li key={item} className="flex items-start gap-2 text-on-surface-variant text-lg">
                      <svg className="w-4 h-4 text-primary mt-1 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </article>

              {/* What is a Serif Font Generator? */}
              <article>
                <h2 className="font-headline text-4xl font-bold mb-8 leading-tight">
                  What is a Serif Font Generator?
                </h2>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  This serif font generator creates serif-inspired text variations from ordinary words. Once your text
                  is entered, you can browse different styles and copy the version that best matches your needs.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  Most online serif text generators use unicode characters to create the appearance of different serif
                  styles. Because these characters are part of the unicode standard, they can often be pasted directly
                  into social media platforms, messaging apps, and online profiles without installing any font files.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-4">
                  People commonly use serif lettering for:
                </p>
                <ul className="space-y-3 mb-6">
                  {[
                    "Social media bios",
                    "Usernames",
                    "Profile names",
                    "Discord nicknames",
                    "Online communities",
                    "Personal branding",
                    "Decorative text in posts and comments",
                  ].map((item) => (
                    <li key={item} className="flex items-start gap-2 text-on-surface-variant text-lg">
                      <svg className="w-4 h-4 text-primary mt-1 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </article>

              {/* Unicode Serif Text vs Traditional Serif Fonts */}
              <article>
                <h2 className="font-headline text-4xl font-bold mb-8 leading-tight">
                  Unicode Serif Text vs Traditional Serif Fonts
                </h2>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-8">
                  Although they may appear similar at first glance, the way they function is quite different.
                </p>

                <h3 className="font-headline text-2xl font-bold mb-4 leading-tight">Unicode Serif Text</h3>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-4">
                  Rather than using installed font files, Unicode serif text relies on alternative character forms that
                  create a decorative serif appearance.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-4">Benefits include:</p>
                <ul className="space-y-3 mb-8">
                  {["Easy copy and paste", "No installation required", "Works on many social platforms", "Great for bios and usernames"].map((item) => (
                    <li key={item} className="flex items-start gap-2 text-on-surface-variant text-lg">
                      <svg className="w-4 h-4 text-primary mt-1 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>

                <h3 className="font-headline text-2xl font-bold mb-4 leading-tight">Traditional Serif Fonts</h3>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-4">
                  Traditional fonts are actual font files used in design software, websites, and documents.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-4">Benefits include:</p>
                <ul className="space-y-3 mb-6">
                  {["Better typography control", "Suitable for branding and print design", "Available in multiple weights and styles", "Ideal for professional design projects"].map((item) => (
                    <li key={item} className="flex items-start gap-2 text-on-surface-variant text-lg">
                      <svg className="w-4 h-4 text-primary mt-1 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>

                <p className="text-on-surface-variant leading-relaxed text-lg">
                  In simple terms, Unicode text is designed for quick online use, while traditional fonts are designed
                  for publishing and graphic design.
                </p>
              </article>

              {/* What Are Serif Fonts? (History & Origins) */}
              <article>
                <h2 className="font-headline text-4xl font-bold mb-8 leading-tight">
                  What Are Serif Fonts? (History &amp; Origins)
                </h2>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  Serif fonts are recognized by the tiny extensions attached to letterforms. These extensions, known as
                  serifs, help create the classic appearance associated with traditional typography.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  Serif lettering has existed for centuries and can be traced back to inscriptions carved into stone
                  during ancient Roman times. The carved letters often featured small extensions at the ends of strokes,
                  which later influenced typography.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  As printing technology evolved, serif typefaces became widely used in books, newspapers, and magazines
                  because they were considered easy to read in long passages.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-6">
                  Today, serif fonts continue to play an important role in publishing, branding, web design, and digital
                  communication.
                </p>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-4">
                  Many organizations use serif text styles to communicate:
                </p>
                <ul className="space-y-3 mb-6">
                  {["Trust", "Tradition", "Authority", "Professionalism", "Class"].map((item) => (
                    <li key={item} className="flex items-start gap-2 text-on-surface-variant text-lg">
                      <svg className="w-4 h-4 text-primary mt-1 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
                <p className="text-on-surface-variant leading-relaxed text-lg">
                  This is why serif lettering remains popular despite the growth of modern <Link href="/sans-serif-fonts" className="text-primary underline">sans-serif typography</Link>.
                </p>
              </article>

              {/* 8 Types of Serif Fonts Explained */}
              <article>
                <h2 className="font-headline text-4xl font-bold mb-8 leading-tight">
                  8 Types of Serif Fonts Explained
                </h2>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-8">
                  Serif typefaces cover a wide range of styles, and each category has its own visual characteristics.
                  Over time, designers created several categories that serve different purposes.
                </p>

                {[
                  {
                    title: "1. Transitional",
                    desc: "Transitional fonts bridge the gap between traditional and modern styles.",
                    examples: ["Lora", "Libre Baskerville", "Merriweather", "Source Serif 4", "Crimson Pro"],
                    note: "These letters offer strong readability and are commonly used for articles, blogs, and editorial content.",
                  },
                  {
                    title: "2. Slab",
                    desc: "Slab serif fonts feature thick and block-like serifs.",
                    examples: ["Roboto Slab", "Bitter", "Zilla Slab", "Crete Round", "Josefin Slab"],
                    note: "They often appear bold, confident, and attention-grabbing.",
                  },
                  {
                    title: "3. Old Style",
                    desc: "Old Style fonts are inspired by early Renaissance typography.",
                    examples: ["EB Garamond", "Cormorant Garamond", "Cardo", "Fraunces", "Spectral"],
                    note: "These classic serif fonts feel traditional and highly readable.",
                  },
                  {
                    title: "4. Modern Serif Fonts",
                    desc: "Modern serif designs often feature dramatic differences in line weight, creating a refined and sophisticated appearance.",
                    examples: ["Old Standard TT", "GFS Didot", "Oranienbaum", "Italiana"],
                    note: "These typefaces often appear neat and sophisticated.",
                  },
                  {
                    title: "5. Humanist",
                    desc: "Humanist styles draw inspiration from handwritten forms.",
                    examples: ["Faustina", "Noto Serif", "Gentium Plus", "Tinos"],
                    note: "They balance readability with a natural appearance.",
                  },
                  {
                    title: "6. Scotch",
                    desc: "Scotch serifs originated in the nineteenth century and remain popular in publishing.",
                    examples: ["Bodoni Moda", "DM Serif Display", "DM Serif Text"],
                    note: "These fonts combine traditional structure with modern refinement.",
                  },
                  {
                    title: "7. Didone",
                    desc: "Didone fonts feature dramatic contrast and refined letterforms.",
                    examples: ["Playfair Display", "Cormorant", "Gloock", "Yeseva One"],
                    note: "They are frequently used in luxury branding and fashion design.",
                  },
                  {
                    title: "8. Fatface",
                    desc: "Fatface typefaces exaggerate contrast and visual impact.",
                    examples: ["Abril Fatface", "Rozha One", "Righteous", "Ultra"],
                    note: "They are often used for headlines and display purposes.",
                  },
                ].map((cat) => (
                  <div key={cat.title} className="mb-10">
                    <h3 className="font-headline text-2xl font-bold mb-4 leading-tight">{cat.title}</h3>
                    <p className="text-on-surface-variant leading-relaxed text-lg mb-4">{cat.desc}</p>
                    <p className="text-on-surface-variant leading-relaxed text-lg mb-2"><strong>Examples:</strong></p>
                    <ul className="space-y-2 mb-4">
                      {cat.examples.map((ex) => (
                        <li key={ex} className="flex items-start gap-2 text-on-surface-variant text-lg">
                          <svg className="w-4 h-4 text-primary mt-1 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>
                          <span>{ex}</span>
                        </li>
                      ))}
                    </ul>
                    <p className="text-on-surface-variant leading-relaxed text-lg">{cat.note}</p>
                  </div>
                ))}
              </article>

              {/* Unicode Serif Styles Available */}
              <article>
                <h2 className="font-headline text-4xl font-bold mb-8 leading-tight">
                  Unicode Serif Styles Available in This Tool
                </h2>
                <p className="text-on-surface-variant leading-relaxed text-lg mb-8">
                  This generator includes 15 Unicode serif-inspired styles.
                </p>
                {[
                  { name: "Bold Serif", desc: <>Strong and highly visible text that stands out in profiles and headings. For more bold styling options beyond serif, try our bold text generator for additional styles.</> },
                  { name: "Italic Serif", desc: "A more elegant style that adds personality and movement." },
                  { name: "Bold Italic Serif", desc: "Combines weight and sophistication." },
                  { name: "Script Serif", desc: <>Inspired by decorative handwriting styles. For dedicated handwriting-style text, explore our <Link href="/cursive-fonts" className="text-primary underline">cursive font generator</Link>.</> },
                  { name: "Bold Script Serif", desc: "A heavier version of script-style text." },
                  { name: "Double Struck", desc: "A mathematical style that creates a unique appearance." },
                  { name: "Fraktur", desc: "Inspired by traditional blackletter typography." },
                  { name: "Bold Fraktur", desc: "A stronger variation of the Fraktur style." },
                  { name: "Small Caps", desc: "Creates a professional and editorial look." },
                  { name: "Wide Serif", desc: "Uses full-width Unicode characters for a unique visual effect." },
                  { name: "Bold Serif Underline", desc: "Adds importance with underlined serif characters." },
                  { name: "Italic Serif Strikethrough", desc: "Useful for creative text styling." },
                  { name: "Circled", desc: "Place letters inside circles." },
                  { name: "Negative Circled", desc: "Uses filled circular letter styles." },
                  { name: "Squared", desc: "Displays characters inside square shapes." },
                ].map((style) => (
                  <div key={style.name} className="mb-6">
                    <h3 className="font-headline text-xl font-bold mb-2 leading-tight">{style.name}</h3>
                    <p className="text-on-surface-variant leading-relaxed text-lg">{style.desc}</p>
                  </div>
                ))}
                <p className="text-on-surface-variant leading-relaxed text-lg mt-4">
                  Since support for unicode characters is not identical across every app and operating system, some
                  styles may appear differently depending on where they are viewed.
                </p>
              </article>

              {/* Serif vs Sans-Serif Table */}
              <article>
                <h2 className="font-headline text-4xl font-bold mb-8 leading-tight">
                  Serif vs Sans-Serif — When to Use Which?
                </h2>
                <div className="overflow-x-auto rounded-xl border border-outline-variant/20 mb-6">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="bg-surface-container-lowest">
                        <th className="p-4 text-left font-headline font-bold text-on-background border-b border-outline-variant/20">Feature</th>
                        <th className="p-4 text-left font-headline font-bold text-on-background border-b border-outline-variant/20">Serif Fonts</th>
                        <th className="p-4 text-left font-headline font-bold text-on-background border-b border-outline-variant/20">Sans-Serif Fonts</th>
                      </tr>
                    </thead>
                    <tbody>
                      {serifVsSansSerif.map((row) => (
                        <tr key={row.feature} className="bg-surface-container-lowest hover:bg-surface-container-low/50 transition-colors">
                          <td className="p-4 font-medium text-on-background border-b border-outline-variant/10 align-top">{row.feature}</td>
                          <td className="p-4 text-on-surface-variant border-b border-outline-variant/10 align-top">{row.serif}</td>
                          <td className="p-4 text-on-surface-variant border-b border-outline-variant/10 align-top">{row.sansSerif}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </article>

              {/* Famous Serif Type Fonts & Their Stories */}
              <article>
                <h2 className="font-headline text-4xl font-bold mb-8 leading-tight">
                  Famous Serif Type Fonts &amp; Their Stories
                </h2>
                {[
                  { name: "Times New Roman", desc: "Originally created for newspaper publishing, Times New Roman became one of the most recognized serif typeface fonts in the world because of its readability and efficient use of space." },
                  { name: "Georgia", desc: "Georgia was designed specifically for screen readability. It remains a popular choice for websites and digital publications." },
                  { name: "Garamond", desc: "Garamond traces its roots back hundreds of years and is still widely admired for its elegance and readability." },
                  { name: "Baskerville", desc: "Baskerville introduced greater contrast and precision, influencing many serif designs that followed." },
                  { name: "Playfair Display", desc: "Playfair Display combines modern and classic influences, making it popular in fashion, luxury, and lifestyle branding." },
                ].map((font) => (
                  <div key={font.name} className="mb-6">
                    <h3 className="font-headline text-xl font-bold mb-2 leading-tight">{font.name}</h3>
                    <p className="text-on-surface-variant leading-relaxed text-lg">{font.desc}</p>
                  </div>
                ))}
              </article>
            </div>

            {/* Sidebar */}
<Sidebar
              showBanner={false}
              useCasesHeading="How to Use a Serif Font Generator?"
              useCasesContent={
                <>
                  <p className="text-sm text-on-surface-variant mb-6 leading-relaxed">
                    Using the tool is simple.
                  </p>
                  <ol className="space-y-4 text-sm leading-relaxed">
                    <li><strong>1. Enter Your Text:</strong> Start by adding the text you want to convert into the text field provided by the generator.</li>
                    <li><strong>2. Browse the Styles:</strong> The generator instantly creates multiple serif style variations.</li>
                    <li><strong>3. Choose a Style:</strong> Select the serif typeface that matches your purpose.</li>
                    <li><strong>4. Copy the Result:</strong> Click or tap the copy button.</li>
                    <li>
                      <strong>5. Paste Anywhere:</strong> Paste the text into supported platforms such as:
                      <ul className="mt-2 space-y-1 list-disc list-inside">
                        <li>Instagram</li>
                        <li>Facebook</li>
                        <li>X (Twitter)</li>
                        <li>Discord</li>
                        <li>TikTok</li>
                        <li>YouTube</li>
                        <li>WhatsApp</li>
                        <li>Telegram</li>
                      </ul>
                    </li>
                  </ol>
                </>
              }
              bottomImage={{ src: "/serif-fonts-explained-visually.webp", alt: "serif fonts explained visually" }}
              tipsHeading="Where to Use Serif Typefaces Online?"
              tipsContent={
                <>
                  <p className="text-sm text-on-surface-variant mb-6 leading-relaxed">
                    Serif type fonts work well in many online environments.
                  </p>
                  <div className="space-y-4 text-sm leading-relaxed">
                    <div>
                      <p className="font-bold text-on-surface">Social Media Bios</p>
                      <p className="text-on-surface-variant">Many users add serif text to make their profiles more unique. For a full collection of styles made specifically for Instagram, visit our <Link href="/instagram-fonts" className="text-primary underline">instagram fonts generator</Link>.</p>
                    </div>
                    <div>
                      <p className="font-bold text-on-surface">Usernames</p>
                      <p className="text-on-surface-variant">A serif username can appear more stylish and memorable.</p>
                    </div>
                    <div>
                      <p className="font-bold text-on-surface">Discord Profiles</p>
                      <p className="text-on-surface-variant">Creative typography helps profiles stand out in communities. See all compatible styles on our discord fonts generator page.</p>
                    </div>
                    <div>
                      <p className="font-bold text-on-surface">Content Creators</p>
                      <p className="text-on-surface-variant">Creators often use decorative text for branding purposes.</p>
                    </div>
                    <div>
                      <p className="font-bold text-on-surface">Digital Portfolios</p>
                      <p className="text-on-surface-variant">Serif styles can contribute to a professional presentation.</p>
                    </div>
                    <div>
                      <p className="font-bold text-on-surface">Personal Branding</p>
                      <p className="text-on-surface-variant">Elegant serif fonts can help create a polished online identity.</p>
                    </div>
                  </div>
                </>
              }
            />
          </div>
        </section>

        {/* Explore Related Fonts */}
        <section className="max-w-[1440px] mx-auto px-4 md:px-[150px] pt-16 pb-8">
          <h2 className="font-headline text-3xl md:text-4xl font-bold mb-8 text-center leading-tight">
            Explore Related Fonts
          </h2>
          <div className="bg-surface-container-lowest border border-outline-variant/40 rounded-2xl editorial-shadow p-6 md:p-8">
            <ul className="flex flex-wrap justify-center gap-3 md:gap-4 list-none p-0 m-0">
              {[
                { label: "Sans Serif Fonts", href: "/sans-serif-fonts" },
                { label: "Cursive Fonts", href: "/cursive-fonts" },
                { label: "Aesthetic Fonts", href: "/" },
              ].map((tool) => (
                <li key={tool.href}>
                  <Link
                    href={tool.href}
                    className="inline-flex items-center px-6 py-3 rounded-full bg-surface-container-low font-body font-medium text-sm md:text-base text-on-surface hover:bg-surface-container hover:text-primary transition-colors"
                  >
                    {tool.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="max-w-[1440px] mx-auto px-4 md:px-[150px] py-24">
          <h2 className="font-headline text-4xl font-bold mb-16 text-center">
            Frequently Asked Questions
          </h2>
          <FAQAccordion faqs={faqs} />
        </section>
      </main>
      <BackToTopButton />
      <Footer />
    </>
  );
}
